version: '3.8'
services:
  mongodb-container:
    container_name: mongodb-container
    image: mongo:latest
    volumes:
      - ./database:/mongo/data
    ports:
      - "27017:27017"
  mysqldbContainer:
    container_name: mysqldbContainer
    image: mysql:latest
    volumes:
      - ./database:/mysql/data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: thcmysqldb
        MYSQL_USER: thcuser
        MYSQL_PASSWORD: thcsql1234
    ports:
      - "3306:3306"
  thc-spring-boot-container:
    container_name: thc-spring-boot-container
    build:
      context: "./"
      dockerfile: "Dockerfile"
    image: sushantcode/thc-spring-boot-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-container
      - mysqldbContainer